---
title: "ggplot2 Train"
output:
  pdf_document: default
  html_document: default
---

```{r, echo=FALSE}
library(ggplot2)
data("diamonds")
data("economics")
data("mpg")

set.seed(233)
dsmall <- diamonds[sample(nrow(diamonds), 300),]
```

```{r}
# functions 
year <- function(dt) {
    as.POSIXlt(dt)$year + 1900
}
```


## qplot
```{r}
# Basic plot
qplot(carat, price, data = dsmall)
qplot(log(carat), log(price), data = dsmall)
qplot(x*y*z, carat, data = dsmall)
qplot(x*y*z, price, data = dsmall)

# color
qplot(carat, price, data = dsmall, colour = color, shape = cut)

qplot(carat, price, data = diamonds, alpha = I(0.05))

# geom type/smooth
qplot(carat, price, data = dsmall, geom = c("point", "smooth"))
qplot(carat, price, data = diamonds, geom = c("point", "smooth"))

# geom type/boxplot
qplot(color, price/carat, data = diamonds, geom = "jitter", alpha = I(1/50))
qplot(color, price/carat, data = diamonds, geom = "boxplot")

# geom type/histogram and density
qplot(carat, data = diamonds, geom = "histogram")
qplot(carat, data = diamonds, geom = "density")

qplot(carat, data = diamonds, geom = "histogram", binwidth = 0.01, xlim = c(0, 3))
qplot(carat, data = diamonds, geom = "histogram", binwidth = 1, xlim = c(0, 3))

qplot(carat, data = diamonds, geom = "histogram", binwidth = 0.01,
      xlim = c(0, 3), colour = color)

qplot(carat, data = diamonds, geom = "density", colour = color)

# geom type/line and path
qplot(date, unemploy/pop, data = economics, geom = "line")
qplot(date, uempmed, data = economics, geom = "line")

qplot(unemploy/pop, uempmed, data = economics, geom = c("point", "path"))

qplot(unemploy/pop, uempmed, data = economics, geom = c("point", "path"),
      colour = year(date))

# facets
qplot(carat, data = diamonds, facets = color ~ ., geom = "histogram",
      binwidth = 0.1, xlim = c(0, 3))
# use density
qplot(carat, ..density.., data = diamonds, facets = color ~ ., geom = "histogram",
      binwidth = 0.1, xlim = c(0, 3))

# plotmath
qplot(carat, price/carat, data = dsmall,
      ylab = expression(frac(price, carat)),
      xlab = "Weight (carats)",
      xlim = c(.2, 1))

qplot(carat, price, data = dsmall, log = "xy")
```

## qplot with layer
```{r}
qplot(displ, hwy, data = mpg, colour = factor(cyl))

qplot(displ, hwy, data = mpg, facets = . ~ year) + geom_smooth(method = "loess")

library(scales)
bestfit <- geom_smooth(method = "lm", se = T, colour = alpha("steelblue", 0.5),
                       size = 2)
qplot(sleep_rem, sleep_total, data = msleep) + bestfit
qplot(awake, brainwt, data = msleep, log = "y") + bestfit
qplot(bodywt, brainwt, data = msleep, log = "xy") +bestfit
```

## ggplot geom
```{r}
p <- ggplot(diamonds, aes(x = carat))
p + geom_histogram(binwidth = 2, fill = "steelblue")

# alt dataset 
p <- ggplot(mtcars, aes(mpg, wt, colour = cyl)) + geom_point() # mapping colour
p %+% transform(mtcars, mpg = mpg^2)

# update eas
p <- ggplot(mtcars, aes(x = mpg, y = wt))
p + geom_point()
p + geom_point(aes(colour = factor(cyl))) # mapping
p + geom_point(aes(y = disp))

# set attr and map attr
p <- ggplot(mtcars, aes(mpg, wt))
p + geom_point(colour = "darkblue")       # set attr
p + geom_point(aes(colour = "darkblue"))  # create str var and mapping

# group
library(nlme)
p <- ggplot(Oxboys, aes(age, height, group = Subject, colour = Subject)) + geom_line()
p + geom_smooth(aes(group = 1), method = "lm", se = F, size = 2)

boysBox <- ggplot(Oxboys, aes(Occasion, height)) + geom_boxplot() # Occasion is default group
boysBox + geom_line(aes(group = Subject), colour = "#3366FF")     # Reset group

# Conformity
d <- ggplot(diamonds, aes(carat)) + xlim(0, 3)
d + stat_bin(aes(ymax = ..count..), binwidth = 0.1, geom = "area")
d + stat_bin(
    aes(size = ..density..),
    binwidth = 0.1,
    geom     = "point",
    position = "identity"
)
d + stat_bin(
    aes(fill = ..count..),
    binwidth = 0.1,
    geom     = "tile",
    position = "identity"
)

# Update attr and dataset
require(nlme, quietly = T, warn.conflicts = F)
model <- lme(height ~ age, data = Oxboys, random = ~ 1 + age | Subject) # redis not random
oplot <- ggplot(Oxboys, aes(age, height, group = Subject)) + geom_line()

age_grid <- seq(-1, 1, length = 10)
subject  <- unique(Oxboys$Subject)
preds <- expand.grid(age = age_grid, Subject = subject)
preds$height <- predict(model, preds)

Oxboys$fitted <- predict(model)
Oxboys$resid  <- with(Oxboys, fitted - height)

oplot + geom_line(data = preds, colour = "#3366FF", size = 0.4)
oplot %+% Oxboys + aes(y = resid) + geom_smooth(aes(group = 1)) # redis not random
#--
model2 <- update(model, height ~ age + I(age^2)) # redis random
Oxboys$fitted2 <- predict(model2)
Oxboys$resid2  <- with(Oxboys, fitted2 - height)

oplot %+% Oxboys + aes(y = resid2) + geom_smooth(aes(group = 1)) # redis random
```

## ggplot stat
```{r}
# use density
# generated var will be around by ..
ggplot(diamonds, aes(carat)) +
    geom_histogram(aes(y = ..density..), binwidth = 0.1)
```
## ggplot2 toolbox 
```{r}
df <- data.frame(
    x     = c(3, 1, 5),
    y     = c(2, 4, 6),
    label = c("a", "b", "c")
)
p <- ggplot(df, aes(x, y)) + xlab(NULL) + ylab(NULL)

p + geom_point() + labs(title = "geom_point")
p + geom_bar(stat = "identity") + labs(title = "geom_bar(\"identity\")")
p + geom_line() + labs(title = "geom_line")
p + geom_area() + labs(title = "geom_area")
p + geom_path() + labs(title = "geom_path")
p + geom_text(aes(label = label)) + labs(title = "geom_text")
p + geom_tile() + labs(title = "geom_tile")
p + geom_polygon() + labs(title = "geom_polygon")

# data distribution
depth_dist <- ggplot(diamonds, aes(depth)) + xlim(58, 68)

depth_dist +
    geom_histogram(aes(y = ..density..), binwidth = 0.1) + facet_grid(cut ~ .)
depth_dist + geom_histogram(aes(fill = cut), binwidth = 0.1, position = "fill")
depth_dist + geom_freqpoly(aes(y = ..density.., colour = cut), binwidth = 0.1)

library(plyr)
qplot(cut, depth, data = diamonds, geom = "boxplot")
qplot(carat, depth, data = diamonds, geom = "boxplot",
      group = round_any(carat, 0.1, floor), xlim = c(0, 3))

qplot(class, cty, data = mpg, geom = "jitter")
qplot(class, drv, data = mpg, geom = "jitter")

qplot(depth, data = diamonds, geom = "density", xlim = c(54, 70))
qplot(depth, data = diamonds, geom = "density", xlim = c(54, 70),
      fill = cut, alpha = I(0.2))

## overplotting
df <- data.frame(x = rnorm(5000), y = rnorm(5000))
norm <- ggplot(df, aes(x, y))
norm + geom_point()
norm + geom_point(shape = 1)
norm + geom_point(shape = ".")
norm + geom_point(alpha = 1/5, colour = "black")

td <- ggplot(diamonds, aes(table, depth)) + xlim(50, 70) + ylim(50, 70)
td + geom_point()
td + geom_jitter()

jit <- position_jitter(width = 0.5)
td + geom_jitter(position = jit)
td + geom_jitter(position = jit, colour = "black", alpha = 1/10)
td + geom_jitter(position = jit, colour = "black", alpha = 1/50)
td + geom_jitter(position = jit, colour = "black", alpha = 1/200)

# bin..
library(hexbin)
d<- ggplot(diamonds, aes(carat, price)) + xlim(1, 3) + 
    theme(legend.position = "none")
d + stat_bin2d()
d + stat_bin2d(bins = 10)
d + stat_bin2d(binwidth = c(0.02, 200))
d + stat_binhex()
d + stat_binhex(bins = 10)
d + stat_binhex(binwidth = c(0.02, 200))

# density2d
d + geom_point()  + geom_density2d()
d + stat_density2d(geom = "point", aes(size = ..density..), contour = F) + scale_size_area()
d + stat_density2d(geom = "tile", aes(fill = ..density..), contour = F)
last_plot() + scale_fill_gradient(limits = c(1e-5, 8e-4))
```

## Uncertainty
```{r}
d <- subset(diamonds, carat < 2.5 & rbinom(nrow(diamonds), 1, 0.2) == 1)
d$lcarat <- log10(d$carat)
d$lprice <- log10(d$price)

detrend <- lm(lprice ~ lcarat, data = d)
d$lprice2 <- resid(detrend)

mod <- lm(lprice2 ~ lcarat * color, data = d)

library(effects)
effectdf <- function(...) {
    suppressWarnings(as.data.frame(effect(...)))
}

color <- effectdf("color", mod)
both1 <- effectdf("lcarat:color", mod)

carat <- effectdf("lcarat", mod, default.levels = 50)
both2 <- effectdf("lcarat:color", mod, default.levels = 3)

qplot(lcarat, lprice, data = d, colour = color)
qplot(lcarat, lprice2, data = d, colour = color)

fplot <- ggplot(mapping = aes(y = fit, ymin = lower, ymax = upper)) + 
    ylim(range(both2$lower, both2$upper))

fplot %+% color + aes(x = color) + geom_point() + geom_errorbar()

fplot %+% both2 +
    aes(x = color, corlour = lcarat, group = interaction(color, lcarat)) +
    geom_errorbar() +
    geom_line(aes(group = lcarat)) +
    scale_color_gradient()

fplot %+% carat + aes(x = lcarat) + geom_smooth(stat = "identity")

end <- subset(both1, lcarat == max(lcarat))
fplot %+% both1 + 
    aes(x = lcarat, colour = color) +
    geom_smooth(stat = "identity") + 
    scale_color_hue() +
    theme(legend.position = "none") +
    geom_text(aes(label = color, x = lcarat + 0.02), end)

```

## Summary
```{r}
midm <- function(x) {
    mean(x, trim = 0.5)
}

require("ggplot2movies")
mov <- movies[sample(nrow(movies), 50000), ]
m2 <- ggplot(mov, aes(x = factor(round(rating)), y = votes)) + geom_point()

m2 + stat_summary(aes(colour = "trimmed"), fun.y = midm, geom = "point") + 
    stat_summary(aes(colour = "raw"), fun.y = mean, geom = "point") +
    scale_color_hue("Mean")

iqr <- function(x, ...) {
    qs <- quantile(as.numeric(x), c(0.25, 0.75), na.rm = T)
    names(qs) <- c("ymin", "ymax")
    qs
}

ggplot(movies, aes(x = year, y = rating)) +
    stat_summary(fun.data = iqr, geom = "ribbon")
```

## Comment
```{r}
unemp <- qplot(date, unemploy, data = economics, geom = "line",
               xlab = "", ylab = "No. unemployed (1000s)")

presidential <- presidential[-(1:3),]
yrng <- range(economics$unemploy)
xrng <- range(economics$date)
unemp + geom_vline(aes(xintercept = as.numeric(start)), data = presidential)

library(scales)
unemp + geom_rect(aes(NULL, NULL, xmin = start, xmax = end, ymin = yrng[1],
                      ymax = yrng[2], fill = party), 
                  data = presidential, alpha = 0.2 ) +
    scale_fill_manual(values = c("blue", "red"))

last_plot() + geom_text(aes(x = start, y = yrng[1], label = name),
                        data = presidential, size = 3, hjust = 0, vjust = 0)

caption <- paste(strwrap("Unemployment rates in the US have varied a lot 
                         over the year", 40), collapse = "\n")
unemp + geom_text(aes(x, y, label = caption),
                  data = data.frame(x = xrng[1], y = yrng[2]),
                  hjust = 0, vjust = 1, size = 4)

height <- subset(economics, unemploy == max(unemploy))
unemp + geom_point(data = height, size = 3, colour = "red", alpha = 0.5)
```

## Weighted data
```{r}
qplot(percwhite, percbelowpoverty, data = midwest)
qplot(percwhite, percbelowpoverty, data = midwest,
      size = poptotal/1e6) + 
    scale_size_area("Population\n(millions)", breaks = c(0.5, 1, 2, 4))

qplot(percwhite, percbelowpoverty, data = midwest, size = area) +
    scale_size_area()

lm_smooth <- geom_smooth(method = "lm", size = 1)
qplot(percwhite, percbelowpoverty, data = midwest) + lm_smooth

qplot(percwhite, percbelowpoverty, data = midwest,
      weight = popdensity, size = popdensity) + lm_smooth

qplot(percbelowpoverty, data = midwest, binwidth = 1)
qplot(percbelowpoverty, data = midwest, weight = poptotal,
      binwidth = 1) + ylab("Population")
```

## Scale
```{r}
(plot <- qplot(cty, hwy, data = mpg))
plot + aes(x = drv)
plot + aes(x = drv) + scale_x_discrete()

(p <- qplot(sleep_total, sleep_cycle, data = msleep, colour = vore))
p + scale_colour_hue()
p + scale_colour_hue("What dose \nit eat?",
    breaks = c("herbi", "carni", "omni", NA),           # mapping breaks 
    labels = c("plants", "meat", "both", "don't know")) # and labels
p + scale_colour_brewer(palette = "Set1")

(p <- qplot(cty, hwy, data = mpg, colour = displ))
p + scale_x_continuous("City mpg")
p + xlab ("City mpg")
p + ylab("Highway mpg")
p + labs(x = "City mpg", y = "Heighway mpg", colour = "Displacement")
p + xlab(expression(frac(miles, gallon)))

(p <- qplot(cyl, wt, data = mtcars))
p + scale_x_continuous(breaks = c(5.5, 6.5))
p + scale_x_continuous(limits = c(5.5, 6.5))

(p <- qplot(wt, cyl, data = mtcars, colour = cyl))
p + scale_colour_gradient(breaks = c(5.5, 6.5))
p + scale_colour_gradient(limits = c(5.5, 6.5))

qplot(log10(carat), log10(price), data = diamonds)
qplot(carat, price, data = diamonds) + 
    scale_x_log10() +
    scale_y_log10()

# date scale
library(scales)
plot <- qplot(date, psavert, data = economics, geom = "line") + 
    ylab("Personal savings rate") +
    geom_hline(xintercept = 0, yintercept = 0, colour = "grey50")
plot

plot + scale_x_date(date_breaks = "10 years")
plot + scale_x_date(
    limits = as.Date(c("2004-01-01", "2005-01-01")),
    date_labels = "%Y-%m-%d"
)

f2d <- with(faithful, MASS::kde2d(eruptions, waiting,
                                  h = c(1, 10), n = 50))
df <- with(f2d, cbind(expand.grid(x, y), as.vector(z)))
names(df) <- c("eruptions", "waiting", "density")
erup <- ggplot(df, aes(eruptions, waiting, fill = density)) +
    geom_tile() +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0))

erup + scale_fill_gradient(limits = c(0, 0.04))
erup + scale_fill_gradient(limits = c(0, 0.04),
                           low = "white", high = "black")
erup + scale_fill_gradient2(limits = c(-0.04, 0.04),
                            midpoint = mean(df$density))

library(vcd)
library(colorspace)
fill_grapn <- function(pal) {
    scale_fill_gradientn(colours = pal(7),
                        limits  = c(0, 0.04))
}

erup + fill_grapn(rainbow_hcl)
erup + fill_grapn(diverge_hcl)
erup + fill_grapn(heat_hcl)

# man discrete scale
colours <- c(carni = "red", "NA" = "orange", insecti = "yellow",
             herbi = "green", omni = "blue")

plot <- qplot(brainwt, bodywt, data = msleep, log = "xy")
plot + aes(colour = vore) +
    scale_colour_manual(values = c("red", "orange", "yellow", "green", "blue"))
plot + aes(colour = vore) + scale_colour_manual(values = colours)
plot + aes(shape = vore) + scale_shape_manual(values = c(1, 2, 6, 0, 23))

huron <- data.frame(year = 1875:1972, level = LakeHuron)
ggplot(huron, aes(year)) + 
    geom_line(aes(y = level - 5, colour = "below")) +
    geom_line(aes(y = level + 5, colour = "above"))

ggplot(huron, aes(year)) + 
    geom_line(aes(y = level - 5, colour = "below")) +
    geom_line(aes(y = level + 5, colour = "above")) +
    scale_colour_manual("Direction",
                values = c("below" = "blue", "above" = "red"))
```

## Facet
```{r}
library(plyr)
library(reshape2)

mpg2 <- subset(mpg, cyl != 5 & drv %in% c("4", "f"))

qplot(cty, hwy, data = mpg2) + facet_grid(drv ~ cyl)

p <- qplot(displ, hwy, data = mpg2) + 
    geom_smooth(method = "lm", se = F)
p + facet_grid(cyl ~ drv)
p + facet_grid(cyl ~ drv, margins = T)

qplot(displ, hwy, data = mpg2) + 
    geom_smooth(aes(colour = drv), method = "lm", se = F) + 
    facet_grid(cyl ~ drv, margins = T)

movies$decade <- round_any(movies$year, 10, floor)
qplot(rating, ..density.., data = subset(movies, decade > 1890),
      geom = "histogram", binwidth = 0.5) +
    facet_wrap(~ decade, ncol = 6)

p <- qplot(cty, hwy, data = mpg)
p + facet_wrap(~ cyl, scales = "free_x")

em <- melt(economics, id = "date")
qplot(date, value, data = em, geom = "line", group = variable) + 
    facet_grid(variable ~ ., scales = "free_y")

# ---
mpg3 <- within(mpg2, {
    model <- reorder(model, cty)
    manufacturer <- reorder(manufacturer, -cty)
})
models <- qplot(cty, model, data = mpg3)
models
models + facet_grid(manufacturer ~ ., scales = "free", space = "free") +
    theme(strip.text.y = element_text())

# facet var loss
xmaj <- c(0.3, 0.5, 1, 3, 5)
xmin <- as.vector(outer(1:10, 10^c(-1, 0)))
ymaj <- c(500, 1000, 5000, 10000)
ymin <- as.vector(outer(1:10, 10^c(2, 3, 4)))
dplot <- ggplot(subset(diamonds, color %in% c("D", "E", "G", "J")),
                aes(carat, price, colour = color)) +
    scale_x_log10(breaks = xmaj, labels = xmaj, minor = xmin) +
    scale_y_log10(breaks = ymaj, labels = ymaj, minor = ymin) +
    scale_colour_hue(limits = levels(diamonds$color)) +
    theme(legend.position = "none")

dplot + geom_point()
dplot + geom_point() + facet_grid(. ~ color)

dplot + geom_smooth(method = "lm", se = F, fullrange = T)
dplot + geom_smooth(method = "lm", se = F, fullrange = T) + 
    facet_grid(. ~ color)

qplot(color, data = diamonds, geom = "bar", fill = cut)
ggplot(diamonds, aes(color, fill = cut)) + 
    geom_bar(position = "dodge") +
    facet_grid(. ~ color, scales = "free") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8,
                                     colour = "grey50"))


mpg4 <- subset(mpg, manufacturer %in% c("audi", "volkswagen", "jeep"))
mpg4$manufacturer <- as.character(mpg4$manufacturer)
mpg4$model <- as.character(mpg4$model)

base <- ggplot(mpg4, aes(fill = model)) + 
    geom_bar(position = "dodge") 

base + aes(x = model) + facet_grid(. ~ manufacturer, scales = "free_x", 
                                   space = "free")
base + aes(x = manufacturer)

# continuous to dispersed
mpg2$displ_ww <- cut_interval(mpg2$displ, length = 1)
mpg2$displ_wn <- cut_interval(mpg2$displ, n = 6)
mpg2$displ_nn <- cut_number(mpg2$displ, n = 6)

plot <- qplot(cty, hwy, data = mpg2) + labs(x = NULL, y = NULL)
plot + facet_wrap(~ displ_ww, nrow = 1)
plot + facet_wrap(~ displ_wn, nrow = 1)
plot + facet_wrap(~ displ_nn, nrow = 1)
```

## coord
```{r}
(p <- qplot(disp, wt, data = mtcars) + geom_smooth())
p + scale_x_continuous(limits = c(325, 500))
p + coord_cartesian(xlim = c(325, 500))

(d <- ggplot(diamonds, aes(carat, price)) + 
        stat_bin2d(bins = 25, colour = "grey70"))
d + scale_x_continuous(limits = c(0, 2))
d + coord_cartesian(xlim = c(0, 2))

qplot(displ, cty, data =mpg) + geom_smooth()
qplot(cty, displ, data = mpg) + geom_smooth()
qplot(cty, displ, data = mpg) + geom_smooth() + coord_flip()

# tran
library(scales)
qplot(carat, price, data = diamonds, log = "xy") + geom_smooth(method = "lm")
qplot(carat, price, data = diamonds) + geom_smooth(method = "lm")
last_plot() + coord_trans(x = exp_trans(10), y = exp_trans(10))

# polar
(pie <- ggplot(mtcars, aes(x = factor(1), fill = factor(cyl))) + 
        geom_bar(width = 1)) 
pie + coord_polar(theta = "y")
pie + coord_polar()
```
## Theme
```{r}
hgram <- qplot(rating, data = movies, binwidth = 1)
previous_them <- theme_set(theme_grey())
hgram
hgram + previous_them
hgram <- hgram + labs(title = "This is a histogram")

hgram + theme(plot.title = element_text(size = 20))
hgram + theme(panel.grid.major = element_line(colour = "red"))
hgram + theme(panel.grid.major = element_line(size = 2))
hgram + theme(panel.grid.major = element_line(linetype = "dotted"))
hgram + theme(axis.line = element_line())
hgram + theme(axis.line = element_line(colour = "red"))
hgram + theme(axis.line = element_line(size = 0.5, linetype = "dashed"))

hgram + theme(plot.background = element_rect(fill = "grey80", colour = NA))
hgram + theme(plot.background = element_rect(size = 2))
hgram + theme(plot.background = element_rect(colour = "red"))
hgram + theme(panel.background = element_rect())
hgram + theme(panel.background = element_rect(colour = NA))
hgram + theme(panel.background = element_rect(linetype = "dotted"))

hgram
last_plot() + theme(panel.grid.major = element_blank())
last_plot() + theme(panel.grid.minor = element_blank())
last_plot() + theme(panel.background = element_blank())
last_plot() + theme(axis.title.x = element_blank(), axis.title.y = element_blank())
last_plot() + theme(axis.line = element_blank())

# ---
old_theme <- theme_update(
    plot.background = element_rect(fill = "#3366FF"),
    panel.background = element_rect(fill = "#003DF5"),
    axis.text.x = element_text(colour = "#CCFF33"),
    axis.text.y = element_text(colour = "#CCFF33", hjust = 1),
    axis.title.x = element_text(colour = "#CCFF33", face = "bold"),
    axis.title.y = element_text(colour = "#CCFF33", face = "bold")
)

qplot(cty, hwy, data = mpg)
theme_set(old_theme)
qplot(cty, hwy, data = mpg)

# scale
p <- qplot(mpg, wt, data = mtcars, colour = factor(cyl))
p
scale_color_discrete <- scale_color_brewer
p

# geom stat 
update_geom_defaults("point", aes(colour = "darkblue"))
qplot(mpg, wt, data = mtcars)
update_stat_defaults("bin", aes(y = ..density..))
qplot(rating, data = movies, geom = "histogram", binwidth = 1)

# save
qplot(mpg, wt, data = mtcars)
ggsave(file = "./images/mtcars.pdf")

(a <- qplot(date, unemploy, data = economics, geom = "line"))
(b <- qplot(uempmed, unemploy, data = economics) + geom_smooth(se = F))
(c <- qplot(uempmed, unemploy, data = economics, geom = "path"))

# sub geom
library(grid)
# define viewport
vp1 <- viewport(width = 1, height = 1, x = 0.5, y = 0.5)
vp2 <- viewport(width = 0.5, height = 0.5, x = 0.5, y = 0.5)
vp3 <- viewport(width = unit(2, "cm"), height = unit(3, "cm"))
vp4 <- viewport(x = 1, y = 1, just = c("top", "right"))
vp4 <- viewport(x = 0, y = 0, just = c("bottom", "right"))

pdf("./images/subplot-1.pdf", width = 4, height = 4)
subvp <- viewport(width = 0.4, height = 0.4, x = 0.75, y = 0.35)
b
print(c, vp = subvp)
dev.off()

csmall <- c + 
    theme_gray(9) +
    labs(x = NULL, y = NULL) + 
    theme(plot.margin = unit(rep(0, 4), "lines") )
pdf("./images/subplot-2.pdf", width = 4, height = 4)
subvp <- viewport(width = 0.4, height = 0.4, x = 0.75, y = 0.35)
b
print(csmall, vp = subvp)
dev.off()

# grid layout
pdf("./images/subplot-3.pdf", width = 8, height = 6)
grid.newpage()
pushViewport(viewport(layout = grid.layout(2,2)))
vplayout <- function(x, y) {
    viewport(layout.pos.row = x, layout.pos.col = y)
}
print(a, vp = vplayout(1, 1:2))
print(b, vp = vplayout(2, 1))
print(c, vp = vplayout(2, 2))
dev.off()
```

## Trick
```{r}
# save ggplot2 plot component to list
xquiet <- scale_x_continuous("", breaks = NULL)
yquiet <- scale_y_continuous("", breaks = NULL)
quiet <- list(xquiet, yquiet)

qplot(mpg, wt, data = mtcars) + quiet
qplot(displ, cty, data = mpg) + quiet

# create ggplot2 component
library(splines)
geom_ml <- function(formula = y~x) {
    geom_smooth(formula = formula, se = F, method = "lm")
}
qplot(mpg, wt, data = mtcars) + geom_ml()
qplot(mpg, wt, data = mtcars) + geom_ml(y ~ ns(x,3))

```

## plot functional
```{r}
library(plyr)
library(reshape2)

range01 <- function(x) {
    rng <- range(x, na.rm = T)
    (x - rng[1])/ diff(rng)
}

pcp_data <- function(df) {
    numeric <- laply(df, is.numeric)
    df[numeric] <- colwise(range01)(df[numeric])
    df$.row <- rownames(df)
    dfm <- melt(df, id = c(".row", names(df)[!numeric]))
    class(dfm) <- c("pcp", class(dfm))
    dfm
}

pcp <- function(df, ...) {
    df <- pcp_data(df)
    ggplot(df, aes(variable, value)) + geom_line(aes(group = .row))
}

pcp(mpg) + aes(colour = drv)
```




