---
title: "R Simulation Notebook"
subtitle: '---R2 simulation'
output:
  pdf_document: default
  html_notebook: default
---

### Buffon simulator
```{r Buffon}
set.seed(233)
buffon.sim <- function(n, l = 0.8, a = 1){
    k     <- 0
    theta <- runif(n, 0, pi)
    x     <- runif(n, 0, a/2)
    
    for(i in 1:n) {
        if(x[i] <= l/2*sin(theta[i]))
            k <- k + 1
    }
    
    sim.pi  <- (2*l*n)/(k*a)
    sim.p   <- k/n
    
    data.frame(pi = sim.pi, p = sim.p)
}

buffon.sim(100000, 0.8, 1)
```

### Area prob simulator
```{r Area prob}
set.seed(233)
area.sim <- function(n) {
    y <- runif(n)
    x <- runif(n)
    k <- 0
    
    for(i in 1:n) {
        if(x[i]^2 + y[i]^2 < 1)
            k <- k + 1
    }
    
    sim.p   <- k/n
    sim.pi  <- 4*sim.p
    
    data.frame(p = sim.p, pi = sim.pi)
}

area.sim(100000)
```

### Trace Simulator
```{r Trace}
plot(c(0, 1, 0, 1), c(0, 0, 1, 1), xlab = "", ylab = "", 
     asp = 1, xlim = c(0, 1), ylim = c(0, 1))
text(0, 1, labels = "A", adj = c(0.3, 1.3))
text(1, 1, labels = "B", adj = c(1.5, 0.5))
text(1, 0, labels = "C", adj = c(0.3, -0.8))
text(0, 0, labels = "D", adj = c(-0.5, 0.1))
points(0.5, 0.5)
text(0.5, 0.5, labels = "O", adj = c(-0.5, 0.3))

delta.t <- 0.01
n       <- 110

x     <- matrix(0, nrow = 5, ncol = n)
y     <- matrix(0, nrow = 5, ncol = n)
x[,1] <- c(0, 1, 1, 0, 0)
y[,1] <- c(1, 1, 0, 0, 1)
d     <- c(0, 0, 0, 0)

for(j in 1:(n-1)) {
    for(i in 1:4){
        d[i] <- sqrt((x[i+1, j]-x[i, j])^2+(y[i+1, j]-y[i, j])^2)
        x[i, j+1] <- x[i, j]+delta.t*(x[i+1, j]-x[i, j])/d[i]
        y[i, j+1] <- y[i, j]+delta.t*(y[i+1, j]-y[i, j])/d[i]
    }
    
    x[5,j+1] <- x[1, j+1]  # For object 4
    y[5,j+1] <- y[1, j+1]  # For object 4
}

for(i in 1:4) {
    lines(x[i,], y[i,])
}
```

### Train simulator
```{r}
gen.t1 <- function(n, r1) {
    t1 <- array(0, dim = c(1, n))
    
    for(i in 1:n) {
        if(r1[i] < 0.7){
            t1[i] <- 0
        } else if(r1[i] <= 0.9) {
            t1[i] = 5
        } else {
            t1[i] = 10
        }
    }
    
    return(t1)
}

gen.t3 <- function(n, r3) {
    t3 <- array(0, dim = c(1, n))
    
    for(i in 1:n) {
        if(r3[i] < 0.3) {
            t3[i] <- 28
        } else if(r3[i] <= 0.7){
            t3[i] <- 30
        } else if(r3[i] <= 0.9) {
            t3[i] = 32
        } else {
            t3[i] = 34
        }
    }
    
    return(t3)
}

train.sim <- function(n) {
    r1 <- runif(n)
    r3 <- runif(n)
    
    t1 <- gen.t1(n, r1)
    t2 <- rnorm(n, 30, 2)
    t3 <- gen.t3(n, r3)
    
    k <- 0
    for(i in 1:n) {
        if(t1[i] + t2[i] > t3[i])
            k <- k+1
    }
    
    return(k/n)
}

train.sim(100000)
```

### Nuclear simulator
```{r}
nuclear.sim <- function(n, d = 3) {
    back   <- 0
    absorb <- 0
    pierce <- 0
    
    for(i in 1:n) {
        x <- -log(runif(1))
        for(j in 1:10) {
            flag <- 1
            r    <- runif(2)
            R    <- -log(r[1])
            t    <- 2*pi*r[2]
            x    <- x+R*cos(t)
            
            if(x < 0) {
                back <- back +1
                flag <- 0
                break
            } else if(x > d) {
                pierce <- pierce +1
                flag   <- 0
                break
            } else
                next
        }
        
        if(flag == 1)
            absorb <- absorb+1
    }
    
    result <- data.frame(Pierce = (pierce/n)*100,
                         Absorb = (absorb/n)*100,
                         Back   = (back/n)*100)
    names(result) <- c("Pierce(%)", "Absorb(%)", "Back(%)")
    return(result)
}

nuclear.sim(10000, 15)
```

### Queue simulator M/M/1/$\infty$
```{r}
gen.expd <- function(lambda) {
    r  <- runif(1)
    -1/lambda*log(r)
}

# lambda: Consumer arrive speed
# mu:     Serve speed 
# TS:     Tatal times
queue.sim <- function(lambda, mu, TS) {
    k  <- 0;  wt <- 0; wn <- 0; ws <- 0;
    tp <- 0;  Na <- 0; n  <- 0; t  <- 0;
    
    # Init simulator
    Ta <- gen.expd(lambda)
    Td <- Inf
    
    repeat{
        # Set system status
        k     <- k+1
        wt[k] <- t
        wn[k] <- n
        
        if(Ta < TS) { # Accept consumer
            ws[k] <- min(Ta, Td)-t
            if(Ta < Td) { # Consumer Arrive
                t  <- Ta
                n  <- n+1
                Na <- Na+1
                Ta <- t+gen.expd(lambda)
                
                if(n == 1)
                    Td <- t+gen.expd(mu) # Set first consumer leave time
            } else { # Consumer leave
                t <- Td
                n <- n-1
                
                if(n == 0)
                    Td <- Inf
                else
                    Td <- t+gen.expd(mu)
            }
        } else { # Reject consumer
            ws[k] <- ifelse(Td == Inf, 0, Td-t)
            if(n>0) { # Serve remain consumer
                t <- Td
                n <- n-1
                if(n>0)
                    Td <- t+gen.expd(mu)
            } else
                tp <- 1
        }
        
        if(tp == 1)
            break
    }
    
    data.frame(Ls = sum(ws*wn)/t,
               Ws = sum(ws*wn)/Na,
               Pw = sum(ws[wn>=1])/t)
}

queue.sim(4, 10, 1000)
```

### Queue simulator M/M/S/$\infty$
```{r}
t.gen <- function(t, lambda) {
    r  <- runif(1)
    t-1/lambda*log(r)
}

queue2.sim <- function(lambda, mu, TS, S) {
    k  <- 0; wt <- 0; wn <- 0; ws <- 0
    tp <- 0; Na <- 0; t  <- 0
    # Init simulator
    Ta <- t.gen(t, lambda)
    Td <- rep(Inf, S)
    SS <- rep(0, S+1)
    
    repeat{
        # Set system status
        t1 <- ifelse(SS[1] == 0, Inf, min(Td))       # Seek leave consumer time
        i1 <- ifelse(SS[1] == 0, 1,   which.min(Td)) # Seek leave consumer idx
        k  <- k+1
        wt[k] <- t
        wn[k] <- SS[1]
        
        if(Ta < TS) { # Accept consumer
            ws[k] <- min(Ta, t1)-t
            if(Ta < t1) {
                t  <- Ta
                Na <- Na+1
                Ta <- t.gen(t, lambda)
                n  <- SS[1]
                SS[1] <- n+1
                
                for(i in 1:S) {  # Dispatch server
                    if(SS[i+1] == 0) {
                        SS[i+1] <- 1
                        Td[i]   <- t.gen(t, mu)
                        break
                    }
                }
            } else { # consumer leave
                t <- t1
                n <- SS[1]
                SS[1] <- n-1
                
                if(n == 1) {        # Clear
                    SS[2:(S+1)] <- 0
                    Td[1:S]     <- Inf
                } else if(n <= S) { # Leave
                    SS[i1+1] <- 0
                    Td[i1]   <- Inf
                } else {            # Leave and alt
                    Td[i1] <- t.gen(t, mu)
                }
            }
        } else { # Reject consumer
            ws[k] <- ifelse(t1 == Inf, 0, t1-t)
            n     <- SS[1]
            
            if(n>0) { # Serve remain consumer
                t     <- t1
                SS[1] <- n-1
                
                if(n == 1) {          # Clear
                    SS[1:(S+1)] <- 0
                    Td[1:S]     <- Inf
                } else if(n <= S) {   # Leave
                    SS[i1+1] <- 0
                    Td[i1]   <- Inf
                } else {              # Leave and alt
                    Td[i1] <- t.gen(t, mu)
                }
            } else # Exit
                tp <- 1
        }
        
        if(tp == 1)
            break
    }
    
    data.frame(Ls = sum(ws*wn)/t,
               Ws = sum(ws*wn)/Na,
               Pw = sum(ws[wn>=S])/t)
}

queue2.sim(15, 6, 1000, 3)
```

### Queue simulator M/M/1/K
```{r}
t.gen <- function(t, lambda) {
    r  <- runif(1)
    t-1/lambda*log(r)
}

queue3.sim <- function(lambda, mu, TS, K = 1) {
    k  <- 0; wt <- 0; wn <- 0; ws <- 0
    tp <- 0; Na <- 0; n  <- 0; t  <- 0
    
    # Init simulator
    Ta <- t.gen(t, lambda)
    Td <- Inf
    
    repeat{
        # Set system status
        k     <- k+1
        wt[k] <- t
        wn[k] <- n
        
        if(Ta < TS) { # Accept consumer
            ws[k] <- min(Ta, Td)-t
            if(Ta <= Td) {
                t  <- Ta
                n  <- n+1
                Na <- Na+1
                Ta <- t.gen(t, lambda)
                
                if(n == 1) # Generate first consumer Leave time
                    Td <- t.gen(t, mu)
                
                if(n == K) # Consumer loss
                    while (Ta < Td)
                        Ta <- t.gen(Ta, lambda)
            } else {       # Consumer leave
                t <- Td
                n <- n-1
                
                if(n == 0)
                    Td <- Inf
                else
                    Td <- t.gen(t, mu)
            }
        } else { # Reject consumer
            ws[k] <- ifelse(Td == Inf, 0, Td-t)
            
            if(n>0) { # Serve remain consumer
                t <- Td
                n <- n-1
                if(n>0)
                    Td <- t.gen(t, mu)
            } else # Exit
                tp <- 1
        }
        
        if(tp == 1)
            break
    }
    
    data.frame(Ls = sum(ws*wn)/t,
               Ws = sum(ws*wn)/Na,
               Pl = sum(ws[wn>=K])/t)
}

queue3.sim(6, 5, 1000, 4)
```

### Queue simulator M/M/S/K
```{r}
set.seed(200)
t.gen <- function(t, lambda) {
    r  <- runif(1)
    t-1/lambda*log(r)
}

queue4.sim <- function(lambda, mu, TS, S = 1, K = 1) {
    if(K<S) K <- S
    k  <- 0; wt <- 0; wn <- 0; ws <- 0
    tp <- 0; Na <- 0; t  <- 0
    # Init simulator
    Ta <- t.gen(t, lambda)
    Td <- rep(Inf, S)
    SS <- rep(0, S+1)
    
    repeat{
        # Set system status
        t1 <- ifelse(SS[1] == 0, Inf, min(Td))
        i1 <- ifelse(SS[1] == 0, 1,   which.min(Td))
        k     <- k+1
        wt[k] <- t
        wn[k] <- SS[1]
        
        if(Ta < TS) { # Accept consumer
            ws[k] <- min(Ta, t1)-t
            
            if(Ta < t1) {
                t     <- Ta
                Na    <- Na+1
                Ta    <- t.gen(t, lambda)
                n     <- SS[1]
                SS[1] <- n+1
                
                if(SS[1] == K) {      # Consumer loss
                    t1 <- min(Td)
                    while(Ta < t1)
                        Ta <- t.gen(Ta, lambda)
                } else {              # Add consumer to system
                    for(i in 1:S) {   # Dispatch server
                        if(SS[i+1] == 0) {
                            SS[i+1] <- 1
                            Td[i]   <- t.gen(t, mu)
                            break
                        }
                    }
                }
            } else { # Consumer leave
                t     <- t1
                n     <- SS[1]
                SS[1] <- n-1
                
                if(n == 1) {       # Cleear
                    SS[2:(S+1)] <- 0
                    Td[1:S]     <- Inf
                } else if(n <= S) { # Consumer leave
                    SS[1+i1] <- 0
                    Td[i1]   <- Inf
                } else {            # Consumer leave and alt
                    Td[i1] <- t.gen(t, mu)
                }
            }
        } else { # Reject consumer
            ws[k] <- ifelse(t1 == Inf, 0, t1-t)
            n     <- SS[1]
            
            if(n > 0) {
                t     <- t1
                SS[1] <- n-1
                
                if(n == 1) {        # Cleear
                    SS[2:(S+1)] <- 0
                    Td[1:S]     <- Inf
                } else if(n <= S) { # Consuemr leave
                    SS[1+i1] <- 0
                    Td[i1]   <- Inf
                } else {            # Consumer leave and alt
                    Td[i1] <- t.gen(t, mu)
                }
            } else # Exit
                tp <- 1
        }
        
        if(tp == 1)
            break
    }
    

    
    data.frame(Ls = sum(ws*wn)/t,
               Ws = sum(ws*wn)/Na,
               Pl = sum(ws[wn>=K])/t)
}

queue4.sim(4, 1/2, 1000, 9, 12)
```



